
apiVersion: v1
kind: Service
metadata:
  name: postgres # Sets service name
  labels:
    app: postgres # Labels and Selectors
spec:
  #type: NodePort # Sets service type
  #type: LoadBalancer
  ports:
    - port: 5432 # Sets port to run the postgres application
      targetPort: 5432
      #nodePort: 30000
  selector:
    app: postgres

